"""
The data required for this figure is generated by the scripts
decision_making_sparse_adjusted.py and decision_making_sparse.py.
"""

import os, h5py, pickle
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.gridspec import GridSpec
import seaborn as sns
cbcolors = sns.color_palette("colorblind").as_hex()

plt.rcParams["font.size"] = 8

## Load simulations with 20% base connectivity

with open("decision_making_sparse_adjusted_results.pkl", "rb") as f:
    res = pickle.load(f)

s1_20 = res["s_NMDA_pre1"].reshape((8, 13, 33, -1)) # 8 simulations, 13 values of inhibitory-selective connectivities, 33 values of intra-selective connectivities
s2_20 = res["s_NMDA_pre2"].reshape((8, 13, 33, -1))

##  Load simulations with varying global connectivity

with open("decision_making_sparse_results.pkl", "rb") as f:
    res = pickle.load(f)

s1_varying_eps = res["s_NMDA_pre1"].reshape((8, 11, -1)) # 8 simulations, 11 different values of global connectivity
s2_varying_eps = res["s_NMDA_pre2"].reshape((8, 11, -1))

## 

s1_20_mean = s1_20[...,4000:].mean((0, -1)) # mean value after network has relaxed
s2_20_mean = s2_20[...,4000:].mean((0, -1)) # mean value after network has relaxed

eps_inh_20 = np.linspace(0.2, 0.5, 13)
eps_sel_20 = np.linspace(0.2, 1.0, 33)

XX_20, YY_20 = np.meshgrid(eps_inh_20, eps_sel_20)

fig, ax = plt.subplots(ncols=2, nrows=3, height_ratios=[1, 1, 1.])
fig.set_size_inches([6,4.5])
fig.subplots_adjust(left=0.08, right=0.9, bottom=0.07, top=0.95, wspace=0.14, hspace=0.6)

ax[0,0].plot(s1_varying_eps[:,10,:].T, cbcolors[0], lw=0.5)
ax[0,0].plot(s2_varying_eps[:,10,:].T, cbcolors[1], lw=0.5)
ax[0,0].set_xlim(1000, 6000)
ax[0,0].sharex(ax[0,1])
ax[0,0].sharey(ax[0,1])

ax[0,1].plot(s1_varying_eps[:,5,:].T, cbcolors[0], lw=0.5)
ax[0,1].plot(s2_varying_eps[:,5,:].T, "C1", lw=0.5)
ax[0,1].set_xlim(1000, 6000)

ax[0,0].set_xlabel("Time [ms]", labelpad=0.5)
ax[0,1].set_xlabel("Time [ms]", labelpad=0.5)

ax[0,0].set_title("100% connectivity", pad=2, fontsize=8)
ax[0,1].set_title("95% connectivity", pad=2, fontsize=8)

# indices for the connectivities to plot
ind1_inh = 3
ind1_sel = 15
ind2_inh = 5
ind2_sel = 23

ax[1,0].plot(s1_20[:,ind1_inh,ind1_sel,:].T, color=cbcolors[0], lw=0.5)
ax[1,0].plot(s2_20[:,ind1_inh,ind1_sel,:].T, color=cbcolors[1], lw=0.5)
ax[1,0].sharex(ax[1,1])
ax[1,0].sharey(ax[1,1])

ax[1,1].plot(s1_20[:,ind2_inh,ind2_sel,:].T, color=cbcolors[0], lw=0.5)
ax[1,1].plot(s2_20[:,ind2_inh,ind2_sel,:].T, color=cbcolors[1], lw=0.5)

ax[1,0].set_title("20% base connectivity, adjusted", pad=2, fontsize=8)
ax[1,1].set_title("20% base connectivity, adjusted", pad=2, fontsize=8)
ax[1,0].set_xlim(1000,6000)
ax[1,0].set_xlabel("Time [ms]", labelpad=0.5)
ax[1,1].set_xlabel("Time [ms]", labelpad=0.5)

pc = ax[2,0].pcolormesh(YY_20.T[:,:], XX_20.T[:,:], s1_20_mean[:,:], vmin=0, vmax=1)
pc = ax[2,1].pcolormesh(YY_20.T[:,:], XX_20.T[:,:], s1_20_mean[:,:] - s2_20_mean[:,:], vmin=0, vmax=1)

ax[2,0].set_aspect(1.)
ax[2,1].set_aspect(1.)

ax[2,0].scatter(eps_sel_20[[ind1_sel, ind2_sel]], eps_inh_20[[ind1_inh, ind2_inh]], c=["red", "blue"], s=5)
ax[2,1].scatter(eps_sel_20[[ind1_sel, ind2_sel]], eps_inh_20[[ind1_inh, ind2_inh]], c=["red", "blue"], s=5)

ax[2,0].set_ylabel("$\mathrm{I} \\to \mathrm{E_A}, \mathrm{I} \\to \mathrm{E_B}$ conn.")
ax[2,0].set_xlabel("$\mathrm{E_A} \\to \mathrm{E_A}, \mathrm{E_B} \\to \mathrm{E_B}$ conn.", labelpad=0.5)
ax[2,1].set_xlabel("$\mathrm{E_A} \\to \mathrm{E_A}, \mathrm{E_B} \\to \mathrm{E_B}$ conn.", labelpad=0.5)

#ax[2,0].set_title("$\mathbb{E}[S_\mathrm{A} - S_\mathrm{B}]$, 50% base connectivity", pad=2, fontsize=8)
ax[2,0].set_title("$\mathbb{E}[S_\mathrm{A}(t)]$, 20% base connectivity", pad=2, fontsize=8)
ax[2,1].set_title("$\mathbb{E}[S_\mathrm{A}(t) - S_\mathrm{B}(t)]$, 20% base connectivity", pad=2, fontsize=8)

ax[2,0].set_xticks(np.linspace(0.2,1,9))
ax[2,0].set_yticks(np.linspace(0.2,0.5,4))
#ax[2,0].set_yticks(np.linspace(0.5,0.7,3))

ax[2,1].set_xticks(np.linspace(0.2,1,9))
ax[2,1].set_yticks(np.linspace(0.2,0.5,4))

cbar_ax = fig.add_axes([0.91,0.075,0.02,0.2])
plt.colorbar(pc, cax=cbar_ax)

labels = ["A", "B", "C", "D", "E", "F"]
for i in range(6):
    ax.flat[i].text(-0.05, 1.05, labels[i], fontsize=11, transform=ax.flat[i].transAxes)

fig.savefig("figure6.pdf")
plt.show()

